# Samsung Galaxy A23 GPS configuration
# Qualcomm bengal

NTP_SERVER=time.google.com
XTRA_SERVER_1=http://xtrapath1.izatcloud.net/xtra3grc.bin
XTRA_SERVER_2=http://xtrapath2.izatcloud.net/xtra3grc.bin
XTRA_SERVER_3=http://xtrapath3.izatcloud.net/xtra3grc.bin
DEFAULT_AGPS_ENABLE=TRUE
DEFAULT_USER_PLANE=TRUE
AGPS_CONFIG_INJECT=TRUE
REPORT_POSITION_USE_SUPL_REFLOC=1
SUPL_VER=0x20000
SUPL_MODE=1
SUPL_ES=1
ACCURACY_THRES=5000
INTERMEDIATE_POS=0
NMEA_PROVIDER=0
CAPABILITIES=0x37
LPP_PROFILE=3
USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=1
A_GLONASS_POS_PROTOCOL_SELECT=0
GPS_LOCK=0
LPPE_CP_TECHNOLOGY=0
LPPE_UP_TECHNOLOGY=0
